format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
hex_literal_case = "Lower"
imports_granularity = "Module"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
